### ISSUE TITLE
-b option for beanstalkd

### ISSUE THREAD

**Issue by StalkAlex** [schickling/dockerfiles#69]
Could you add variant with binary log and volume?

**Comment by alexxd35** [comment]
I want to add the -b option in docker-compose,and i had tried
command: beanstalkd -b /some/dir
but it doesn't work.
could you tell me how to use the -b option in docker-compose.yml?

  beanstalkd:
    image: schickling/beanstalkd:latest
#    command: beanstalkd -b /etc/beanstalkdlog    (this command doesn't work)
    volumes:
      - ${BEANSTALKD_LOG}:/etc/beanstalkdlog:ro
    ports:
      - "${BEANSTALKD_HOST_PORT}:11300"
    networks:
      - default

**Comment by xxy123456** [comment]
I have the same problem, have you solved it？

**Comment by uchagani** [comment]
please see this comment that explains how to use this: https://github.com/schickling/dockerfiles/issues/107#issuecomment-444124965

to use with docker-compose add your volume and add a command like this:

```
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    volumes:
      - /opt/docker/beanstalkd-data:/data
    ports:
      - 11300:11300
    command: "-p 11300 -b /data"
```
